name: Build lol-pyshock

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile lol-pyshock.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lol-pyshock
        path: dist/lol-pyshock.exe
